version: '3.8'
services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ea_user
      POSTGRES_PASSWORD: ea_pass
      POSTGRES_DB: ea_db
    ports:
      - '5432:5432'
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
