version: '3.8'
services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: easyaccess
      POSTGRES_PASSWORD: easyaccess
      POSTGRES_DB: easyaccess
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
