[project]
name = "ea-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.2"
dependencies = [
    "openpyxl",
    "typer",
    "rich",
    "polars[sqlalchemy]",
    "python-dotenv",
    "fastexcel",
    "xlsxwriter",
    "trogon",
    "httpx",
    "lxml",
    "bs4",
    "pyyaml",
    "loguru",
    "colorama",
    "nameparser",
    "levenshtein",
    "selenium",
    "google-genai",
    "aiometer",
    "ea-cli",
    "tortoise-orm[accel]",
    "python-fasthtml",
    "monsterui",
    "pypdf",
    "xxhash",
    "qdrant-client[fastembed]",
    "pdfreader",
    "pikepdf",
    "kreuzberg[paddleocr]",
    "uvicorn",
    "ruff",
    "pymupdf4llm",
    "pytesseract",
    "gliner>=0.2.17",
    "langchain-text-splitters>=0.3.8",
    "flashtext>=2.7",
    "fastlite>=0.1.3",
    "spacy>=3.8.5",
    "spacy-layout>=0.0.12",
    "pyinstaller>=6.13.0",
    "pythonnet>=3.0.5",
    "pywebview>=5.4",
    "cefpython3>=66.1",
]

[tool.uv.sources]
ea-cli = { workspace = true }


[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["F405", "E501", "F403"]
