[project]
name = "ea-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.2"
dependencies = [
    "pyyaml",
    "levenshtein",
    "openpyxl",
    "typer",
    "polars[sqlalchemy]",
    "xlsxwriter",
    "httpx",
    "bs4",
    "loguru",
    "aiometer",
    "tortoise-orm[accel]",
    "tqdm",
    "fastexcel>=0.15.1",
]

[tool.uv]
default-groups = ["dev"]

[dependency-groups]

tui = [
    "trogon"
]

dev = [
    {include-group="lint"},
    {include-group="test"}
]

lint = [
    "ruff",
    "ty",
]
test = [
    "pytest",
    "pytest-asyncio",
]

pdf = [
    "xxhash",
    "kreuzberg[crypto]",
]


dashboard = [
    "fastlite",
    "fastcore",
    "starlette",
    "monsterui",
    "python-fasthtml",
]

[tool.uv.sources]
ea-cli = { workspace = true }

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["F405", "E501", "F403"]
