[project]
name = "ea-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [

    "openpyxl>=3.1.5",

    "typer>=0.12.5",

    "rich>=13.8.1",

    "polars[sqlalchemy]>=1.7.1",

    "python-dotenv>=1.0.1",

    "fastexcel>=0.11.6",

    "xlsxwriter>=3.2.0",

    "trogon>=0.6.0",

    "httpx>=0.28.1",

    "lxml>=5.3.0",

    "bs4>=0.0.2",

    "pyyaml",

    "loguru",

    "colorama",

    "nameparser",

    "levenshtein",

    "pipe>=2.2",

    "selenium",

    "transformers>=4.48.0",

    "torch>=2.6.0",

    "scikit-learn>=1.6.1",

    "evaluate>=0.4.3",

    "spacy-layout>=0.0.11",

    "spacy>=3.8.4",

    "google-genai>=1.2.0",

    "aiometer>=0.5.0",

    "uvicorn>=0.34.0",

    "fastapi>=0.115.8",

    "pdfminer-six>=20240706",

    "ea-cli",
]

[tool.uv.sources]
ea-cli = { workspace = true }
