"""
create initial schema

Revision ID: f2355a540318
Revises: None
Create Date: 2025-10-13 13:38:38.761487
"""

# revision identifiers, used by Alembic.
revision = "f2355a540318"
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_details', sa.JSON(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_updates'))
    )
    op.create_table('missing_courses',
    sa.Column('cursuscode', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cursuscode', name=op.f('pk_missing_courses'))
    )
    op.create_table('organization_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_organization_id', sa.Integer(), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.Column('abbreviation', sa.String(length=255), nullable=False),
    sa.Column('full_abbreviation', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['parent_organization_id'], ['organization_data.id'], name=op.f('fk_organization_data_parent_organization_id_organization_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_data')),
    sa.UniqueConstraint('full_abbreviation', name=op.f('uq_organization_data_full_abbreviation')),
    sa.UniqueConstraint('name', 'abbreviation', name='uq_organization_name_abbr')
    )
    op.create_index(op.f('ix_organization_data_abbreviation'), 'organization_data', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_organization_data_name'), 'organization_data', ['name'], unique=False)
    op.create_table('pdf_canvas_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=2048), nullable=False),
    sa.Column('filename', sa.String(length=2048), nullable=False),
    sa.Column('upload_status', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('mime_class', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('download_url', sa.String(length=2048), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('canvas_created_at', sa.DateTime(), nullable=False),
    sa.Column('canvas_updated_at', sa.DateTime(), nullable=False),
    sa.Column('canvas_modified_at', sa.DateTime(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('lock_at', sa.DateTime(), nullable=True),
    sa.Column('unlock_at', sa.DateTime(), nullable=True),
    sa.Column('visibility_level', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_anonymous_id', sa.String(length=255), nullable=True),
    sa.Column('user_display_name', sa.String(length=2048), nullable=True),
    sa.Column('user_avatar_image_url', sa.String(length=2048), nullable=True),
    sa.Column('user_html_url', sa.String(length=2048), nullable=True),
    sa.Column('user_pronouns', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_canvas_metadata'))
    )
    op.create_table('pdf_entity_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.String(length=2048), nullable=False),
    sa.Column('canonical_form', sa.String(length=2048), nullable=True),
    sa.Column('recognized', sa.Boolean(), nullable=False),
    sa.Column('recognition_type', sa.Enum('EMPLOYEE', 'AUTHOR', 'PUBLISHER', 'ORGANIZATION', name='entitytypes'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_entity_data'))
    )
    op.create_table('pdf_text_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('text_quality', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_text_data'))
    )
    op.create_table('copyright_data',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('2020_1A', '2020_1B', '2020_2A', '2020_2B', '2020_3', '2020_SEM1', '2020_SEM2', '2020_JAAR', '2021_1A', '2021_1B', '2021_2A', '2021_2B', '2021_3', '2021_SEM1', '2021_SEM2', '2021_JAAR', '2022_1A', '2022_1B', '2022_2A', '2022_2B', '2022_3', '2022_SEM1', '2022_SEM2', '2022_JAAR', '2023_1A', '2023_1B', '2023_2A', '2023_2B', '2023_3', '2023_SEM1', '2023_SEM2', '2023_JAAR', '2024_1A', '2024_1B', '2024_2A', '2024_2B', '2024_3', '2024_SEM1', '2024_SEM2', '2024_JAAR', '2025_1A', '2025_1B', '2025_2A', '2025_2B', '2025_3', '2025_SEM1', '2025_SEM2', '2025_JAAR', '2026_1A', '2026_1B', '2026_2A', '2026_2B', '2026_3', '2026_SEM1', '2026_SEM2', '2026_JAAR', '2027_1A', '2027_1B', '2027_2A', '2027_2B', '2027_3', '2027_SEM1', '2027_SEM2', '2027_JAAR', '2028_1A', '2028_1B', '2028_2A', '2028_2B', '2028_3', '2028_SEM1', '2028_SEM2', '2028_JAAR', '2029_1A', '2029_1B', '2029_2A', '2029_2B', '2029_3', '2029_SEM1', '2029_SEM2', '2029_JAAR', '2030_1A', '2030_1B', '2030_2A', '2030_2B', '2030_3', '2030_SEM1', '2030_SEM2', '2030_JAAR', name='period'), nullable=False),
    sa.Column('department', sa.String(length=2048), nullable=False),
    sa.Column('course_code', sa.String(length=255), nullable=False),
    sa.Column('course_name', sa.String(length=2048), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=2048), nullable=True),
    sa.Column('owner', sa.String(length=2048), nullable=True),
    sa.Column('filetype', sa.Enum('PDF', 'PPT', 'DOC', 'XLSX', 'MP4', 'JPG', 'PNG', 'UNKNOWN', 'FILE', name='filetype'), nullable=False),
    sa.Column('classification', sa.Enum('OPEN_ACCESS', 'KORTE_OVERNAME', 'MIDDELLANGE_OVERNAME', 'LANGE_OVERNAME', 'EIGEN_MATERIAAL_POWERPOINT', 'EIGEN_MATERIAAL_TITELINDICATIE', 'EIGEN_MATERIAAL_OVERIG', 'EIGEN_MATERIAAL', 'ONBEKEND', 'NIET_GEANALYSEERD', 'IN_ONDERZOEK', 'VERWIJDERVERZOEK_VERSTUURD', 'LICENTIE_BESCHIKBAAR', name='classification'), nullable=False),
    sa.Column('ml_prediction', sa.Enum('OPEN_ACCESS', 'KORTE_OVERNAME', 'MIDDELLANGE_OVERNAME', 'LANGE_OVERNAME', 'EIGEN_MATERIAAL_POWERPOINT', 'EIGEN_MATERIAAL_TITELINDICATIE', 'EIGEN_MATERIAAL_OVERIG', 'EIGEN_MATERIAAL', 'ONBEKEND', 'NIET_GEANALYSEERD', 'IN_ONDERZOEK', 'VERWIJDERVERZOEK_VERSTUURD', 'LICENTIE_BESCHIKBAAR', name='classification'), nullable=True),
    sa.Column('manual_classification', sa.String(length=2048), nullable=True),
    sa.Column('manual_identifier', sa.String(length=2048), nullable=True),
    sa.Column('v2_manual_classification', sa.Enum('JA_OPEN_LICENTIE', 'JA_BIBLIOTHEEK_LICENTIE', 'JA_DIRECTE_TOESTEMMING', 'JA_PUBLIEK_DOMEIN', 'JA_EIGEN_WERK', 'JA_STUDENTWERK', 'JA_EASY_ACCESS', 'JA_ANDERS', 'JA_DIRECTE_TOESTEMMING_TIJDELIJK', 'JA_BIBLIOTHEEK_LICENTIE_TIJDELIJK', 'JA_ANDERS_TIJDELIJK', 'NEE_LINK_BESCHIKBAAR', 'NEE_STUDENTWERK', 'NEE', 'ONBEKEND', name='classificationv2'), nullable=True),
    sa.Column('v2_overnamestatus', sa.Enum('OVERNAME_INBREUKMAKENDE', 'OVERNAME_ANDERE', 'GEEN_OVERNAME', 'ONBEKEND', name='overnamestatus'), nullable=True),
    sa.Column('v2_lengte', sa.Enum('KORT', 'MIDDELLANG', 'LANG', 'ONBEKEND', name='lengte'), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=10000), nullable=True),
    sa.Column('auditor', sa.String(length=10000), nullable=True),
    sa.Column('last_change', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PUBLISHED', 'UNPUBLISHED', 'DELETED', name='status'), nullable=False),
    sa.Column('isbn', sa.String(length=255), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('in_collection', sa.Boolean(), nullable=True),
    sa.Column('pagecount', sa.Integer(), nullable=False),
    sa.Column('wordcount', sa.Integer(), nullable=False),
    sa.Column('picturecount', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=2048), nullable=True),
    sa.Column('publisher', sa.String(length=2048), nullable=True),
    sa.Column('reliability', sa.Integer(), nullable=False),
    sa.Column('pages_x_students', sa.Integer(), nullable=False),
    sa.Column('count_students_registered', sa.Integer(), nullable=False),
    sa.Column('filehash', sa.String(length=255), nullable=True),
    sa.Column('last_scan_date_university', sa.Date(), nullable=True),
    sa.Column('last_scan_date_course', sa.Date(), nullable=True),
    sa.Column('retrieved_from_copyright_on', sa.DateTime(), nullable=True),
    sa.Column('workflow_status', sa.Enum('ToDo', 'Done', 'InProgress', name='workflowstatus'), nullable=False),
    sa.Column('possible_fine', sa.Float(), nullable=True),
    sa.Column('infringement', sa.Enum('YES', 'NO', 'MAYBE', 'UNDETERMINED', name='infringement'), nullable=False),
    sa.Column('file_exists', sa.Boolean(), nullable=True),
    sa.Column('last_canvas_check', sa.DateTime(), nullable=True),
    sa.Column('canvas_course_id', sa.Integer(), nullable=True),
    sa.Column('faculty_abbreviation', sa.String(length=255), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_abbreviation'], ['organization_data.abbreviation'], name=op.f('fk_copyright_data_faculty_abbreviation_organization_data')),
    sa.PrimaryKeyConstraint('material_id', name=op.f('pk_copyright_data')),
    sa.UniqueConstraint('url', name=op.f('uq_copyright_data_url'))
    )
    op.create_index(op.f('ix_copyright_data_canvas_course_id'), 'copyright_data', ['canvas_course_id'], unique=False)
    op.create_index(op.f('ix_copyright_data_course_code'), 'copyright_data', ['course_code'], unique=False)
    op.create_index(op.f('ix_copyright_data_course_name'), 'copyright_data', ['course_name'], unique=False)
    op.create_index(op.f('ix_copyright_data_department'), 'copyright_data', ['department'], unique=False)
    op.create_index(op.f('ix_copyright_data_filename'), 'copyright_data', ['filename'], unique=False)
    op.create_index(op.f('ix_copyright_data_is_duplicate'), 'copyright_data', ['is_duplicate'], unique=False)
    op.create_index(op.f('ix_copyright_data_manual_classification'), 'copyright_data', ['manual_classification'], unique=False)
    op.create_index(op.f('ix_copyright_data_ml_prediction'), 'copyright_data', ['ml_prediction'], unique=False)
    op.create_index(op.f('ix_copyright_data_remarks'), 'copyright_data', ['remarks'], unique=False)
    op.create_index(op.f('ix_copyright_data_retrieved_from_copyright_on'), 'copyright_data', ['retrieved_from_copyright_on'], unique=False)
    op.create_index(op.f('ix_copyright_data_status'), 'copyright_data', ['status'], unique=False)
    op.create_index(op.f('ix_copyright_data_v2_lengte'), 'copyright_data', ['v2_lengte'], unique=False)
    op.create_index(op.f('ix_copyright_data_v2_manual_classification'), 'copyright_data', ['v2_manual_classification'], unique=False)
    op.create_index(op.f('ix_copyright_data_v2_overnamestatus'), 'copyright_data', ['v2_overnamestatus'], unique=False)
    op.create_index(op.f('ix_copyright_data_workflow_status'), 'copyright_data', ['workflow_status'], unique=False)
    op.create_table('course_data',
    sa.Column('cursuscode', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('faculty_abbreviation', sa.String(length=255), nullable=True),
    sa.Column('ec', sa.Float(), nullable=True),
    sa.Column('programme', sa.String(length=2048), nullable=True),
    sa.Column('notes', sa.String(length=10000), nullable=True),
    sa.Column('category', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['faculty_abbreviation'], ['organization_data.abbreviation'], name=op.f('fk_course_data_faculty_abbreviation_organization_data')),
    sa.PrimaryKeyConstraint('cursuscode', name=op.f('pk_course_data')),
    sa.UniqueConstraint('internal_id', name=op.f('uq_course_data_internal_id'))
    )
    op.create_table('person_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_name', sa.String(length=2048), nullable=False),
    sa.Column('main_name', sa.String(length=2048), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('first_name', sa.String(length=2048), nullable=True),
    sa.Column('email', sa.String(length=2048), nullable=True),
    sa.Column('faculty_abbreviation', sa.String(length=255), nullable=True),
    sa.Column('people_page_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['faculty_abbreviation'], ['organization_data.abbreviation'], name=op.f('fk_person_data_faculty_abbreviation_organization_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_data'))
    )
    op.create_index(op.f('ix_person_data_input_name'), 'person_data', ['input_name'], unique=True)
    op.create_table('programme_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_abbreviation', sa.String(length=255), nullable=True),
    sa.Column('cluster', sa.String(length=2048), nullable=True),
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.Column('abbreviation', sa.String(length=255), nullable=False),
    sa.Column('programme_type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['faculty_abbreviation'], ['organization_data.abbreviation'], name=op.f('fk_programme_data_faculty_abbreviation_organization_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programme_data')),
    sa.UniqueConstraint('name', 'abbreviation', name='uq_programme_name_abbr')
    )
    op.create_index(op.f('ix_programme_data_abbreviation'), 'programme_data', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_programme_data_name'), 'programme_data', ['name'], unique=False)
    op.create_table('copyright_item_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copyright_item_id', sa.Integer(), nullable=False),
    sa.Column('course_cursuscode', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['copyright_item_id'], ['copyright_data.material_id'], name=op.f('fk_copyright_item_course_copyright_item_id_copyright_data')),
    sa.ForeignKeyConstraint(['course_cursuscode'], ['course_data.cursuscode'], name=op.f('fk_copyright_item_course_course_cursuscode_course_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copyright_item_course'))
    )
    op.create_table('copyright_item_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copyright_item_id', sa.Integer(), nullable=False),
    sa.Column('item_update_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['copyright_item_id'], ['copyright_data.material_id'], name=op.f('fk_copyright_item_update_copyright_item_id_copyright_data')),
    sa.ForeignKeyConstraint(['item_update_id'], ['item_updates.id'], name=op.f('fk_copyright_item_update_item_update_id_item_updates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copyright_item_update'))
    )
    op.create_table('course_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_cursuscode', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['course_cursuscode'], ['course_data.cursuscode'], name=op.f('fk_course_employee_course_cursuscode_course_data')),
    sa.ForeignKeyConstraint(['person_id'], ['person_data.id'], name=op.f('fk_course_employee_person_id_person_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_employee'))
    )
    op.create_table('v1_copyright_item',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('matching_copyright_item_id', sa.Integer(), nullable=True),
    sa.Column('workflow_status', sa.Enum('ToDo', 'Done', 'InProgress', name='workflowstatus'), nullable=False),
    sa.Column('retrieved_from_copyright_on', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('manual_classification', sa.String(length=2048), nullable=True),
    sa.Column('remarks', sa.String(length=10000), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('faculty', sa.String(length=255), nullable=True),
    sa.Column('ml_prediction', sa.Enum('OPEN_ACCESS', 'KORTE_OVERNAME', 'MIDDELLANGE_OVERNAME', 'LANGE_OVERNAME', 'EIGEN_MATERIAAL_POWERPOINT', 'EIGEN_MATERIAAL_TITELINDICATIE', 'EIGEN_MATERIAAL_OVERIG', 'EIGEN_MATERIAAL', 'ONBEKEND', 'NIET_GEANALYSEERD', 'IN_ONDERZOEK', 'VERWIJDERVERZOEK_VERSTUURD', 'LICENTIE_BESCHIKBAAR', name='classification'), nullable=True),
    sa.Column('filename', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=2048), nullable=True),
    sa.Column('filehash', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=2048), nullable=True),
    sa.Column('period', sa.Enum('2020_1A', '2020_1B', '2020_2A', '2020_2B', '2020_3', '2020_SEM1', '2020_SEM2', '2020_JAAR', '2021_1A', '2021_1B', '2021_2A', '2021_2B', '2021_3', '2021_SEM1', '2021_SEM2', '2021_JAAR', '2022_1A', '2022_1B', '2022_2A', '2022_2B', '2022_3', '2022_SEM1', '2022_SEM2', '2022_JAAR', '2023_1A', '2023_1B', '2023_2A', '2023_2B', '2023_3', '2023_SEM1', '2023_SEM2', '2023_JAAR', '2024_1A', '2024_1B', '2024_2A', '2024_2B', '2024_3', '2024_SEM1', '2024_SEM2', '2024_JAAR', '2025_1A', '2025_1B', '2025_2A', '2025_2B', '2025_3', '2025_SEM1', '2025_SEM2', '2025_JAAR', '2026_1A', '2026_1B', '2026_2A', '2026_2B', '2026_3', '2026_SEM1', '2026_SEM2', '2026_JAAR', '2027_1A', '2027_1B', '2027_2A', '2027_2B', '2027_3', '2027_SEM1', '2027_SEM2', '2027_JAAR', '2028_1A', '2028_1B', '2028_2A', '2028_2B', '2028_3', '2028_SEM1', '2028_SEM2', '2028_JAAR', '2029_1A', '2029_1B', '2029_2A', '2029_2B', '2029_3', '2029_SEM1', '2029_SEM2', '2029_JAAR', '2030_1A', '2030_1B', '2030_2A', '2030_2B', '2030_3', '2030_SEM1', '2030_SEM2', '2030_JAAR', name='period'), nullable=True),
    sa.Column('department', sa.String(length=2048), nullable=True),
    sa.Column('course_code', sa.String(length=255), nullable=True),
    sa.Column('course_name', sa.String(length=2048), nullable=True),
    sa.Column('filetype', sa.Enum('PDF', 'PPT', 'DOC', 'XLSX', 'MP4', 'JPG', 'PNG', 'UNKNOWN', 'FILE', name='filetype'), nullable=False),
    sa.Column('classification', sa.Enum('OPEN_ACCESS', 'KORTE_OVERNAME', 'MIDDELLANGE_OVERNAME', 'LANGE_OVERNAME', 'EIGEN_MATERIAAL_POWERPOINT', 'EIGEN_MATERIAAL_TITELINDICATIE', 'EIGEN_MATERIAAL_OVERIG', 'EIGEN_MATERIAAL', 'ONBEKEND', 'NIET_GEANALYSEERD', 'IN_ONDERZOEK', 'VERWIJDERVERZOEK_VERSTUURD', 'LICENTIE_BESCHIKBAAR', name='classification'), nullable=False),
    sa.Column('manual_identifier', sa.String(length=2048), nullable=True),
    sa.Column('auditor', sa.String(length=10000), nullable=True),
    sa.Column('last_change', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PUBLISHED', 'UNPUBLISHED', 'DELETED', name='status'), nullable=False),
    sa.Column('isbn', sa.String(length=255), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('in_collection', sa.Boolean(), nullable=True),
    sa.Column('pagecount', sa.Integer(), nullable=False),
    sa.Column('wordcount', sa.Integer(), nullable=False),
    sa.Column('picturecount', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=2048), nullable=True),
    sa.Column('publisher', sa.String(length=2048), nullable=True),
    sa.Column('reliability', sa.Integer(), nullable=False),
    sa.Column('pages_x_students', sa.Integer(), nullable=False),
    sa.Column('count_students_registered', sa.Integer(), nullable=False),
    sa.Column('cursuscodes', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['matching_copyright_item_id'], ['copyright_data.material_id'], name=op.f('fk_v1_copyright_item_matching_copyright_item_id_copyright_data')),
    sa.PrimaryKeyConstraint('material_id', name=op.f('pk_v1_copyright_item'))
    )
    op.create_index(op.f('ix_v1_copyright_item_course_code'), 'v1_copyright_item', ['course_code'], unique=False)
    op.create_index(op.f('ix_v1_copyright_item_course_name'), 'v1_copyright_item', ['course_name'], unique=False)
    op.create_index(op.f('ix_v1_copyright_item_department'), 'v1_copyright_item', ['department'], unique=False)
    op.create_index(op.f('ix_v1_copyright_item_manual_classification'), 'v1_copyright_item', ['manual_classification'], unique=False)
    op.create_index(op.f('ix_v1_copyright_item_status'), 'v1_copyright_item', ['status'], unique=False)
    op.create_table('pdf_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copyright_item_id', sa.Integer(), nullable=True),
    sa.Column('v1_copyright_item_id', sa.Integer(), nullable=True),
    sa.Column('canvas_metadata_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=2048), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('retrieved_on', sa.DateTime(), nullable=True),
    sa.Column('current_file_name', sa.String(length=2048), nullable=False),
    sa.Column('author', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=2048), nullable=True),
    sa.Column('subject', sa.String(length=2048), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('producer', sa.String(length=2048), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('mod_date', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.String(length=2048), nullable=True),
    sa.Column('summary', sa.String(length=10000), nullable=True),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('filehash', sa.String(length=255), nullable=True),
    sa.Column('extraction_attempted', sa.Boolean(), nullable=False),
    sa.Column('extraction_successful', sa.Boolean(), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('num_words', sa.Integer(), nullable=True),
    sa.Column('num_images', sa.Integer(), nullable=True),
    sa.Column('extracted_text_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['canvas_metadata_id'], ['pdf_canvas_metadata.id'], name=op.f('fk_pdf_data_canvas_metadata_id_pdf_canvas_metadata')),
    sa.ForeignKeyConstraint(['copyright_item_id'], ['copyright_data.material_id'], name=op.f('fk_pdf_data_copyright_item_id_copyright_data')),
    sa.ForeignKeyConstraint(['extracted_text_id'], ['pdf_text_data.id'], name=op.f('fk_pdf_data_extracted_text_id_pdf_text_data')),
    sa.ForeignKeyConstraint(['v1_copyright_item_id'], ['v1_copyright_item.material_id'], name=op.f('fk_pdf_data_v1_copyright_item_id_v1_copyright_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_data'))
    )
    op.create_index(op.f('ix_pdf_data_filehash'), 'pdf_data', ['filehash'], unique=False)
    op.create_table('pdf_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['pdf_entity_data.id'], name=op.f('fk_pdf_entity_entity_id_pdf_entity_data')),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf_data.id'], name=op.f('fk_pdf_entity_pdf_id_pdf_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_entity'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_entity')
    op.drop_index(op.f('ix_pdf_data_filehash'), table_name='pdf_data')
    op.drop_table('pdf_data')
    op.drop_index(op.f('ix_v1_copyright_item_status'), table_name='v1_copyright_item')
    op.drop_index(op.f('ix_v1_copyright_item_manual_classification'), table_name='v1_copyright_item')
    op.drop_index(op.f('ix_v1_copyright_item_department'), table_name='v1_copyright_item')
    op.drop_index(op.f('ix_v1_copyright_item_course_name'), table_name='v1_copyright_item')
    op.drop_index(op.f('ix_v1_copyright_item_course_code'), table_name='v1_copyright_item')
    op.drop_table('v1_copyright_item')
    op.drop_table('course_employee')
    op.drop_table('copyright_item_update')
    op.drop_table('copyright_item_course')
    op.drop_index(op.f('ix_programme_data_name'), table_name='programme_data')
    op.drop_index(op.f('ix_programme_data_abbreviation'), table_name='programme_data')
    op.drop_table('programme_data')
    op.drop_index(op.f('ix_person_data_input_name'), table_name='person_data')
    op.drop_table('person_data')
    op.drop_table('course_data')
    op.drop_index(op.f('ix_copyright_data_workflow_status'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_v2_overnamestatus'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_v2_manual_classification'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_v2_lengte'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_status'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_retrieved_from_copyright_on'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_remarks'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_ml_prediction'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_manual_classification'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_is_duplicate'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_filename'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_department'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_course_name'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_course_code'), table_name='copyright_data')
    op.drop_index(op.f('ix_copyright_data_canvas_course_id'), table_name='copyright_data')
    op.drop_table('copyright_data')
    op.drop_table('pdf_text_data')
    op.drop_table('pdf_entity_data')
    op.drop_table('pdf_canvas_metadata')
    op.drop_index(op.f('ix_organization_data_name'), table_name='organization_data')
    op.drop_index(op.f('ix_organization_data_abbreviation'), table_name='organization_data')
    op.drop_table('organization_data')
    op.drop_table('missing_courses')
    op.drop_table('item_updates')
    # ### end Alembic commands ###
