from enum import StrEnum, auto


class Url(StrEnum):
    """
    Enum for routes in the dashboard module.
    """

    root = auto()
    data_grid = auto()
    logout = auto()
    show_item_details = auto()
    get_entities_element = auto()
    get_pdf_element = auto()
    get_extracted_text_element = auto()
    save_item_details = auto()
    get_file = auto()
    get_osiris_data = auto()


# Dictionary to hold URL strings after they are generated by the routes
URLS: dict[Url, str] = {}
